server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple_rss_viewer
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    schema: public
logging:
  level:
    root: INFO
mybatis:
  mapper-locations: classpath*:mapper/*.xml
feeds-update:
  thread:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 40

